### ISSUE TITLE
Error message while compiling example 

### ISSUE THREAD

**Issue by JoePython1** [yuriizinets/kyoto#73]
# command-line-arguments
./main.go:15:9: undefined: mktemplate

**Comment by yuriizinets** [comment]
Seems like you're trying to use example from `README.md`.  
I've mentioned: "This example is not completely independent and just shows what the code looks like when using kyoto".  

Unfortunately, kyoto have pretty huge entry barrier because library created for complex project setup.  
Please, check demo project here: https://github.com/yuriizinets/kyoto/tree/master/.demo  
Or use "Example with guide", you can find it in documentation here: https://kyoto.codes/example-with-guide.html
